name: Publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: Build, pack & publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      # Publish
      - name: Publish com.etsoo.EasyPdf on version change
        uses: alirezanet/publish-nuget@v3.1.0
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: com.etsoo.EasyPdf/com.etsoo.EasyPdf.csproj

          # Flag to toggle git tagging, enabled by default
          TAG_COMMIT: false

          # API key to authenticate with NuGet server
          NUGET_KEY: ${{secrets.ETSOONugetKey}}
